In [2]:
import numpy as np

In [ ]:
arr=np.array((1,2,3,4,5,6,7,8))

In [4]:
print(arr)

[1 2 3 4 5 6 7 8]


In [6]:
arr2d=np.array([[1,2,3],[4,5,6]])

In [7]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])

In [9]:
print(arr3d)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [11]:
print(arr.ndim)

1


In [12]:
print(arr2d.ndim)

2


In [14]:
print(arr3d.ndim)

3


In [15]:
print(arr[::2])

[1 3 5 7]


In [16]:
print(arr[::-1])

[8 7 6 5 4 3 2 1]


In [ ]:
print(arr[-9:-1])

[1 2 3 4 5 6 7]


In [25]:
print(arr2d[1,::-1])

[6 5 4]


In [26]:
print(arr2d[:,2])

[3 6]


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
x=arr.copy()
arr[0]=23
print(arr)
print(x)
print(x.base)

[23  2  3  4  5  6  7  8  9 10]
[23  2  3  4  5  6  7  8  9 10]
None


In [37]:
x=arr.view()
arr[0]=23
print(arr)
print(x)
print(x.base)


[23  2  3  4  5  6  7  8  9 10]
[23  2  3  4  5  6  7  8  9 10]
[23  2  3  4  5  6  7  8  9 10]


In [38]:
print(arr.shape)
print(arr2d.shape)
print(arr3d.shape)


(10,)
(2, 3)
(2, 2, 3)


In [48]:
arr.reshape(5,2)

array([[23,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [52]:
arr.reshape(5,-1)

array([[23,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [53]:
arr2d.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [55]:
for i in np.nditer(arr3d):
    print(i)

1
2
3
4
5
6
7
8
9
1
2
3
